// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sellora.NotificationService.Infrastructure.Persistence;

#nullable disable

namespace Sellora.NotificationService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260927182039_AddDispatchState")]
    partial class AddDispatchState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sellora.NotificationService.Domain.Entities.NotificationRecipient", b =>
                {
                    b.Property<Guid>("NotificationRecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_recipient_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("delivery_status");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("NotificationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_request_id");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("provider_message_id");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("NotificationRecipientId")
                        .HasName("pk_notification_recipient");

                    b.HasIndex("NotificationRequestId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("uq_notification_recipient_request_kind");

                    b.ToTable("notification_recipient", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_recipient_delivery_status", "delivery_status IN ('Pending', 'Sent', 'Failed', 'Unaddressed')");

                            t.HasCheckConstraint("ck_notification_recipient_kind", "kind IN ('Shop', 'Agency')");
                        });
                });

            modelBuilder.Entity("Sellora.NotificationService.Domain.Entities.NotificationRequest", b =>
                {
                    b.Property<Guid>("NotificationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_request_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ClaimedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_until");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_reference");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTimeOffset?>("RenderedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rendered_at");

                    b.Property<string>("RenderedBodySha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rendered_body_sha256");

                    b.Property<string>("RenderedHtml")
                        .HasColumnType("text")
                        .HasColumnName("rendered_html");

                    b.Property<string>("RenderedSubject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rendered_subject");

                    b.Property<string>("RenderedText")
                        .HasColumnType("text")
                        .HasColumnName("rendered_text");

                    b.Property<int?>("SendGapMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("send_gap_ms");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<long>("SourceOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("source_offset");

                    b.Property<int>("SourcePartition")
                        .HasColumnType("integer")
                        .HasColumnName("source_partition");

                    b.Property<string>("SourceTopic")
                        .IsRequired()
                        .HasMaxLength(249)
                        .HasColumnType("character varying(249)")
                        .HasColumnName("source_topic");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template_key");

                    b.HasKey("NotificationRequestId")
                        .HasName("pk_notification_request");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("uq_notification_request_source_event");

                    b.HasIndex("CompanyId", "OrderId")
                        .HasDatabaseName("ix_notification_request_company_order");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_notification_request_dispatch_due");

                    b.HasIndex("Status", "ReceivedAt")
                        .HasDatabaseName("ix_notification_request_status_received");

                    b.ToTable("notification_request", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_request_status", "status IN ('Pending', 'Sent', 'PartiallySent')");
                        });
                });

            modelBuilder.Entity("Sellora.NotificationService.Domain.Entities.NotificationRecipient", b =>
                {
                    b.HasOne("Sellora.NotificationService.Domain.Entities.NotificationRequest", null)
                        .WithMany("Recipients")
                        .HasForeignKey("NotificationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_recipient_request");
                });

            modelBuilder.Entity("Sellora.NotificationService.Domain.Entities.NotificationRequest", b =>
                {
                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
